class CityData {
  List<String> cities = [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Palerme',
    'Gênes',
    'Bologne',
    'Florence',
    'Venise',
    'Vérone',
    'Messine',
    'Padoue',
    'Trieste',
    'Bari',
    'Catane',
    'Brescia',
    'Parme',
    'Prato',
    'Modène',
    'Reggio de Calabre',
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Le Havre',
    'Saint-Étienne',
    'Toulon',
    'Grenoble',
    'Dijon',
    'Angers',
    'Nîmes',
    'Villeurbanne',
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphie',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'San Francisco',
    'Columbus',
    'Indianapolis',
    'Fort Worth',
    'Charlotte',
    'Seattle',
    'Denver',
    'Washington, D.C.',
    'Bruxelles',
    'Anvers',
    'Gand',
    'Charleroi',
    'Liège',
    'Bruges',
    'Namur',
    'Louvain',
    'Malines',
    'Alost',
    'La Louvière',
    'Courtrai',
    'Hasselt',
    'Ostende',
    'Tournai',
    'Genk',
    'Seraing',
    'Roulers',
    'Molenbeek-Saint-Jean',
    'Schaerbeek',
    'Toronto',
    'Montréal',
    'Vancouver',
    'Calgary',
    'Edmonton',
    'Ottawa',
    'Québec',
    'Winnipeg',
    'Hamilton',
    'Kitchener',
    'London',
    'St. Catharines',
    'Halifax',
    'Oshawa',
    'Victoria',
    'Windsor',
    'Saskatoon',
    'Regina',
    'Sherbrooke',
    'St. John\'s',
    'Moscou',
    'Saint-Pétersbourg',
    'Novossibirsk',
    'Ekaterinbourg',
    'Nijni Novgorod',
    'Kazan',
    'Tcheliabinsk',
    'Omsk',
    'Samara',
    'Rostov-sur-le-Don',
    'Oufa',
    'Krasnoïarsk',
    'Voronej',
    'Perm',
    'Volgograd',
    'Krasnodar',
    'Saratov',
    'Tolyatti',
    'Izhevsk',
    'Orenbourg',
  ];
}

final cityData = CityData();
